services:
  app:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    working_dir: /app
    entrypoint: ./entrypoint.sh
    command: "rails s -b 0.0.0.0"
    depends_on:
      - "postgres"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
    env_file: 
      - .env

  postgres:
    image: postgres
    restart: always                                                                                                                                                                                  
    volumes:
      - fast_order_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  bundle:
  fast_order_pgdata:
