version: '3.8'
services:
  app:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    working_dir: /app
    entrypoint: ./entrypoint.sh
    command: "rails s -b 0.0.0.0"
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
    env_file: 
      - .env
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app

  esbuild:
    build:
      context: .
      target: dev
    command: "yarn build --watch=forever"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - app

  postgres:
    image: postgres
    restart: always
    volumes:
      - fast_order_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  bundle:
  fast_order_pgdata:
