default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: 'postgres,localhost'

development:
  <<: *default
  database: fast_order_development

test:
  <<: *default
  database: fast_order_test

production:
  <<: *default
  database: fast_order_production
  username: fast_order
  password: <%= ENV["FAST_ORDER_DATABASE_PASSWORD"] %>

