default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *default
  database: fast_order_development

test:
  <<: *default
  database: fast_order_test

production:
  <<: *default
  database: fast_order_production
  username: fast_order
  password: <%= ENV["FAST_ORDER_DATABASE_PASSWORD"] %>
